import "./globals.css";
import { Inter } from "next/font/google";
import { ReduxProvider } from "../components/ReduxProvider/ReduxProvier";
import { ReactNode } from "react";
import { defaultLocale } from "../../middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: { children: ReactNode; params: { lang: string } }) {
  return (
    <html lang={params.lang ?? defaultLocale}>
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
