name: test and deploy vercel
 
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  UnitTests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # клонируем репозиторый
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test

  Lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn lint

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [UnitTests, Lint]
    steps:
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: run tests
     
